# Generated by Django 4.0 on 2022-01-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок новости')),
                ('content', models.TextField(max_length=2000, verbose_name='содержание статьи')),
                ('image', models.ImageField(upload_to='', verbose_name='изображение статьи')),
                ('published', models.DateField(auto_now=True)),
                ('type', models.CharField(max_length=20, verbose_name='тип новостей')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
            },
        ),
    ]
